name: Backloggd Android App (Unofficial)
description: An Android application for the website backloggd.com. Essentially, it's a wrapper for the website using a WebView.
full_description: '<b>v1.2 (Aug 7, 2024)</b><br>
<br>- Added support for Themed icons on Android 13+
<br>- UI fixes and improvements
<br>
<br><b>v1.1 (Mar 11, 2024)</b><br>
<br>- Now you can add a background color and change the size: 1:1, 4:3, 9:16 for Instagram Stories, 2:1 for Twitter, 1.91:1 for LinkedIn
<br>
<br><b>v1.0 (Feb 16, 2024)</b><br>
<br>- Added a new overview video to Google Play'
android: false
iOS: false
web: false
GitHub: https://github.com/wagenknecht/Backloggd-Android-App/releases
screenshots:
  - 01-screenshot.png
  - 02-screenshot.png
  - 03-screenshot.png
  - 04-screenshot.png
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
